import { afterEach, expect, it, vi } from 'vitest';
import { Connection, Keypair, PublicKey, SystemProgram, Transaction } from '@solana/web3.js';
import nacl from 'tweetnacl';
import { fetchDurableNonceInfo } from '../common/nonce';
import { HotPathExecutor, TransactionBuilder } from '../hotpath';
afterEach(() => vi.restoreAllMocks());
it.each([true,false])('cached durable nonce keeps advance first (gas=%s), signs two authorities and uses no read RPC', async gas => {
  const payer=Keypair.generate(), authority=Keypair.generate(), nonce=Keypair.generate().publicKey;
  const data=Buffer.alloc(80);data.writeUInt32LE(1,0);data.writeUInt32LE(1,4);
  authority.publicKey.toBuffer().copy(data,8);Keypair.generate().publicKey.toBuffer().copy(data,40);
  const info=await fetchDurableNonceInfo({getAccountInfo:async()=>({data,owner:SystemProgram.programId,executable:false})} as any,nonce);
  expect(info).not.toBeNull();
  const rpc=vi.spyOn(Connection.prototype,'getLatestBlockhash').mockImplementation(()=>{throw Error('implicit RPC');});
  const network=vi.spyOn(globalThis,'fetch').mockImplementation(()=>{throw Error('implicit network');});
  const executor=new HotPathExecutor(new Connection('http://localhost:1'),{enablePrefetch:false});
  vi.spyOn(executor,'getBlockhash').mockReturnValue({blockhash:info!.nonceHash,lastValidBlockHeight:0});
  const builder=new TransactionBuilder(executor);
  const instructions=[SystemProgram.nonceAdvance({noncePubkey:nonce,authorizedPubkey:authority.publicKey})];
  const tx=(await builder.buildTransaction(payer.publicKey,instructions,[authority,payer],gas ? {computeUnitLimit:200000,computeUnitPrice:1} : undefined))!;
  expect(tx.instructions[0]!.programId.equals(SystemProgram.programId)).toBe(true);
  expect(tx.instructions[0]!.data.readUInt32LE(0)).toBe(4);
  expect(instructions).toHaveLength(1);
  const parsed=Transaction.from(tx.serialize());expect(parsed.recentBlockhash).toBe(info!.nonceHash);
  expect(parsed.instructions[0]!.keys[0]!.pubkey.equals(nonce)).toBe(true);
  expect(parsed.instructions[0]!.keys[2]!.pubkey.equals(authority.publicKey)).toBe(true);
  for(const signature of parsed.signatures)expect(nacl.sign.detached.verify(parsed.serializeMessage(),signature.signature!,signature.publicKey.toBytes())).toBe(true);
  await expect(builder.buildTransaction(payer.publicKey,instructions,[payer])).rejects.toThrow('Missing required');
  expect(rpc).not.toHaveBeenCalled();expect(network).not.toHaveBeenCalled();
});
